// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: ha_display

#ifndef _HA_DISPLAY_UI_H
#define _HA_DISPLAY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_screen1
void ui_screen1_screen_init(void);
extern lv_obj_t * ui_screen1;
extern lv_obj_t * ui_label1;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_hand_png);    // assets/hand.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
