// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: ha_display

#include "../ui.h"

void ui_screen1_screen_init(void)
{
    ui_screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_screen1, &ui_img_hand_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label1 = lv_label_create(ui_screen1);
    lv_obj_set_width(ui_label1, lv_pct(100));
    lv_obj_set_height(ui_label1, lv_pct(100));
    lv_obj_set_align(ui_label1, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_label1, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_label1, "Hello, Pumpkin and Frogface!");
    lv_obj_set_style_text_font(ui_label1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

}
